version: '3.4'

services:
  database:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    ports:
      - '8123:8123'
    volumes:
      - ./db:/var/lib/clickhouse

  app:
    build:
      context: ./
      dockerfile: main.Dockerfile
    environment:
      - DB_HOST=database
    container_name: app
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8080"
    depends_on:
      - database
    ports:
      - '8080:8080'
